config/routes.rb
Rails.application.routes.draw do
  
  root 'users#index'
  resources :users, only: [:index, :show, :destroy]
  get 'all', to:'users#all'
  get 's', to:'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    # @serach = request
    # puts '------------'
    # puts @serach.ip
    # puts @serach.user_agent
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :destroy]

  # GET /users
  # GET /users.json
  def index
    user = User.new
    user.ip = request.ip
    user.port = request.port
    user.url = request.url
    user.host = request.host
    user.referer = request.referer
    user.agent = request.user_agent
    user.save
  end

  def all
    @users = User.order("id desc").page(params[:page]).per(40)
  end


  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  # def edit
  # end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html><html><head><title>my</title><%= csrf_meta_tags %><%= csp_meta_tag %><style>table{border:2px solid #42b983;border-radius:3px;cursor:pointer;// background-color:#fff;font-size:9px}th{background-color:#42b983;color:rgba(255,255,255,0.66);//cursor:pointer}td{// background-color:#f9f9f9;color:#726868}th.active{color:#fff}th.active .arrow{opacity:1}tr:hover{color:#000;// font-weight:bold;background-color:#f4faa4}.arrow{display:inline-block;vertical-align:middle;width:0;height:0;margin-left:5px;opacity:.66}.arrow.asc{border-left:4px solid transparent;border-right:4px solid transparent;border-bottom:4px solid #fff}.arrow.dsc{border-left:4px solid transparent;border-right:4px solid transparent;border-top:4px solid #fff}</style><script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script><script src="https://cdn.jsdelivr.net/npm/rails-ujs@5.2.0/lib/assets/compiled/rails-ujs.min.js"></script></head><body><%= yield %></body></html>

app/views/search/index.html.erb
<%= User.count %>条记录
～～～～～～～～～～
<%= link_to '返回', root_path %>

app/views/users/_paginate.html.erb
<% if(@users.total_pages rescue nil) %>
    <%= paginate @users , remote: true%>
<% end %>

app/views/users/_user.html.erb
<table class="table">
  <thead>
    <tr>
      <th>time</th>
      <th>Url</th>
      <th>Ip</th>
      <th>Port</th>
      <th>Host</th>
      <th>Referer</th>
      <th>Agent</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
        <tr id='<%= user.id %>'>
            <td title='<%= user.created_at %>'><%= user.created_at.to_s(:short)%></td>
            <td title='<%= user.url %>'><%= user.url.split('/')[3..-1].join('/') %></td>
            <td><%= link_to user.ip, user%></td>
            <td><%= user.port %></td>
            <td><%= user.host %></td>
            <% if user.referer %>
            <td title='<%= user.referer %>'><%= user.referer.split('/')[3..-1].join('/') %></td>
            <% else %>
            <td></td>
            <% end %>
            <% if user.agent %>
            <td title='<%=user.agent%>'><%= user.agent[0..25] %></td>
            <% else %>
            <td></td>
            <% end %>
            <td><%= link_to '╳', user, style:"color: red;", data: { method: :delete, remote: true} %></td>
        </tr>
    <% end %>
  </tbody>
</table>

app/views/users/all.js.erb
$('#user table').remove();
$('#paginate nav').remove();
$('#user').append('<%= j render 'user' %>');
$('#paginate').append('<%= j render 'paginate' %>');

app/views/users/destroy.js.erb
$("table tr#<%= @user.id %>").remove();
$("#notice").text('User was successfully destroyed.');

app/views/users/index.html.erb
<p style="color: red;" id="notice">
  <%= notice %>
</p>
<div id='paginate'></div>
<hr style="height:1px;border:none;border-top:1px solid #555555;" />
<div id='user'></div>
<p> <%= link_to '查找', s_path %></p>
<script>
$(function () {
    $.get('/all');
})
</script>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Url:</strong>
  <%= @user.url %>
</p>

<p>
  <strong>Ip:</strong>
  <%= @user.ip %>
</p>

<p>
  <strong>Port:</strong>
  <%= @user.port %>
</p>

<p>
  <strong>Host:</strong>
  <%= @user.host %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @user.agent %>
</p>
<%= link_to 'Back', users_path %>